<script setup lang="ts">
import {
  Globe,
  Laptop,
  MonitorCheck,
  Smartphone,
  Tablet,
  Terminal,
} from 'lucide-vue-next'

import {
  AcerIcon,
  AndroidIcon,
  AppleIcon,
  AppleTvIcon,
  ArchLinuxIcon,
  ArcIcon,
  AsusIcon,
  BaiduIcon,
  BlackberryIcon,
  BraveIcon,
  CentOsIcon,
  DebianIcon,
  DellIcon,
  DiscordIcon,
  DuckDuckGoIcon,
  EricssonIcon,
  FacebookIcon,
  FedoraIcon,
  FirefoxBrowserIcon,
  FitbitIcon,
  FreeBsdIcon,
  FujitsuIcon,
  GarminIcon,
  GnuIcon,
  GoogleCastIcon,
  GoogleChromeIcon,
  GoogleIcon,
  GoogleTvIcon,
  HonorIcon,
  HpIcon,
  HtcIcon,
  HuaweiIcon,
  IOsIcon,
  LenovoIcon,
  LgIcon,
  LinuxIcon,
  LinuxMintIcon,
  LogitechIcon,
  MacOsIcon,
  MeizuIcon,
  MetaIcon,
  MotorolaIcon,
  NecIcon,
  NokiaIcon,
  NotionIcon,
  NvidiaIcon,
  OculusIcon,
  OnePlusIcon,
  OpenAiIcon,
  OperaGxIcon,
  OperaIcon,
  OppoIcon,
  PanasonicIcon,
  PinterestIcon,
  PlayStationIcon,
  QqIcon,
  RazerIcon,
  RedHatIcon,
  RokuIcon,
  SafariIcon,
  SamsungIcon,
  SharpIcon,
  SlackIcon,
  SonyIcon,
  SteamIcon,
  TelegramIcon,
  TeslaIcon,
  TikTokIcon,
  TorBrowserIcon,
  ToshibaIcon,
  UbuntuIcon,
  ValveIcon,
  VivaldiIcon,
  VivoIcon,
  WearOsIcon,
  WeChatIcon,
  XiaomiIcon,
  XIcon,
  YandexCloudIcon,
} from 'vue3-simple-icons'

withDefaults(defineProps<{
  name: string
  type?: string
}>(), {
  type: 'browser',
})

const iconMaps: Record<string, Component> = {
  'acer': AcerIcon,
  'android': AndroidIcon,
  'android browser': AndroidIcon,
  'apple tv': AppleTvIcon,
  'applebot': AppleIcon,
  'arc': ArcIcon,
  'arch': ArchLinuxIcon,
  'arch linux': ArchLinuxIcon,
  'asus': AsusIcon,
  'baidu': BaiduIcon,
  'baidu browser': BaiduIcon,
  'baiduspider': BaiduIcon,
  'blackberry': BlackberryIcon,
  'brave': BraveIcon,
  'browser': Globe,
  'centos': CentOsIcon,
  'chrome': GoogleChromeIcon,
  'chrome headless': GoogleChromeIcon,
  'chrome webview': GoogleChromeIcon,
  'chromecast': GoogleCastIcon,
  'chromium': GoogleChromeIcon,
  'claudebot': OpenAiIcon,
  'console': SteamIcon,
  'curl': Terminal,
  'debian': DebianIcon,
  'dell': DellIcon,
  'desktop': MonitorCheck,
  'discord': DiscordIcon,
  'discordbot': DiscordIcon,
  'duckduckbot': DuckDuckGoIcon,
  'duckduckgo': DuckDuckGoIcon,
  'ericsson': EricssonIcon,
  'facebook': FacebookIcon,
  'facebookexternalhit': FacebookIcon,
  'fedora': FedoraIcon,
  'firefox': FirefoxBrowserIcon,
  'firefox focus': FirefoxBrowserIcon,
  'firefox reality': FirefoxBrowserIcon,
  'fitbit': FitbitIcon,
  'freebsd': FreeBsdIcon,
  'fujitsu': FujitsuIcon,
  'garmin': GarminIcon,
  'gnu': GnuIcon,
  'google': GoogleIcon,
  'google tv': GoogleTvIcon,
  'googlebot': GoogleIcon,
  'googlebot-image': GoogleIcon,
  'gptbot': OpenAiIcon,
  'harmonyos': HuaweiIcon,
  'honor': HonorIcon,
  'hp': HpIcon,
  'htc': HtcIcon,
  'huawei': HuaweiIcon,
  'huawei browser': HuaweiIcon,
  'ios': IOsIcon,
  'ipad': AppleIcon,
  'iphone': AppleIcon,
  'ipod': AppleIcon,
  'laptop': Laptop,
  'lenovo': LenovoIcon,
  'lg': LgIcon,
  'linux': LinuxIcon,
  'linux mint': LinuxMintIcon,
  'logitech': LogitechIcon,
  'macintosh': AppleIcon,
  'macos': MacOsIcon,
  'meizu': MeizuIcon,
  'meta': MetaIcon,
  'mint': LinuxMintIcon,
  'miui browser': XiaomiIcon,
  'mobile': Smartphone,
  'mobile chrome': GoogleChromeIcon,
  'mobile firefox': FirefoxBrowserIcon,
  'mobile safari': SafariIcon,
  'motorola': MotorolaIcon,
  'nec': NecIcon,
  'nokia': NokiaIcon,
  'notion': NotionIcon,
  'nvidia': NvidiaIcon,
  'oculus': OculusIcon,
  'oculus browser': OculusIcon,
  'oneplus': OnePlusIcon,
  'opera': OperaIcon,
  'opera coast': OperaIcon,
  'opera gx': OperaGxIcon,
  'opera mini': OperaIcon,
  'opera mobi': OperaIcon,
  'opera touch': OperaIcon,
  'oppo': OppoIcon,
  'os': MonitorCheck,
  'panasonic': PanasonicIcon,
  'pico': OculusIcon,
  'pico browser': OculusIcon,
  'pinterestbot': PinterestIcon,
  'playstation': PlayStationIcon,
  'qqbrowser': QqIcon,
  'razer': RazerIcon,
  'realme': OppoIcon,
  'red hat': RedHatIcon,
  'redhat': RedHatIcon,
  'roku': RokuIcon,
  'safari': SafariIcon,
  'samsung': SamsungIcon,
  'samsung internet': SamsungIcon,
  'sharp': SharpIcon,
  'slackbot': SlackIcon,
  'smarttv': GoogleTvIcon,
  'sony': SonyIcon,
  'tablet': Tablet,
  'telegrambot': TelegramIcon,
  'tesla': TeslaIcon,
  'tiktok': TikTokIcon,
  'tiktok lite': TikTokIcon,
  'tor browser': TorBrowserIcon,
  'toshiba': ToshibaIcon,
  'twitterbot': XIcon,
  'ubuntu': UbuntuIcon,
  'valve': ValveIcon,
  'vivaldi': VivaldiIcon,
  'vivo': VivoIcon,
  'vivo browser': VivoIcon,
  'wearable': WearOsIcon,
  'wechat': WeChatIcon,
  'xiaomi': XiaomiIcon,
  'xr': MetaIcon,
  'yandex': YandexCloudIcon,
  'yandexbot': YandexCloudIcon,
}
</script>

<template>
  <div class="w-full truncate">
    <component
      :is="iconMaps[name.toLowerCase()] || iconMaps[type]"
      class="float-left h-5 w-5 py-0.5"
    />
    <span>{{ name }}</span>
  </div>
</template>
